spring:
  application:
    name: Backend
  datasource:
    url: jdbc:mysql://localhost:3306/learnsite?useSSL=false&serverTimezone=UTC
    username: root
    password: 362426wxf..07
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
server:
  port: 8000
